name: CI/CD to EC2 with Docker
on:
  push:
    branches:
      - main
    # v2 도 만들어야함.
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create application-secret.properties
        run: |
          echo "${{ secrets.APPLICATION_SECRET_PROPERTIES }}" > src/main/resources/application-secret.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Tests
        run: ./gradlew test

  deploy:
    name: Build Docker JAR and Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create application-secret.properties
        run: |
          echo "${{ secrets.APPLICATION_SECRET_PROPERTIES }}" > src/main/resources/application-secret.properties                 

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ureca-final-project-dockerhub/user-backend-image:${{github.sha}} .
          docker push ureca-final-project-dockerhub/user-backend-image:${{ github.sha }}

      - name: Save EC2 SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy JAR to EC2 and Run
        run: |
        # todo : ec2 접속 해서
          docker pull my-dockerhub/my-app:${{ github.sha }}
          docker stop my-app || true
          docker rm my-app || true
          docker run -d --name my-app -p 8082:8082 ureca-final-project-dockerhub/user-backend-image:${{ github.sha }}